/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-2:4ea459ea-f730-4f05-85a1-0b4d1055db5b",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_qOTxJ0LrJ",
  aws_user_pools_web_client_id: "14lko9a53qmvlo6k6ta81qrd3h",
  oauth: {},
  aws_cloud_logic_custom: [
    {
      name: "AdminQueries",
      endpoint: "https://nxffy42c6k.execute-api.us-west-2.amazonaws.com/dev",
      region: "us-west-2"
    }
  ],
  aws_appsync_graphqlEndpoint:
    "https://6srpde2f6nfvnavqqvmthfq57y.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_user_files_s3_bucket: "bucket-onway154115-dev",
  aws_user_files_s3_bucket_region: "us-west-2"
};

export default awsmobile;
